nome = str(input('Digite seu nome completo: ')).strip()
print(f'Seu nome com letras maiusculas: {nome.upper()}.')
print(f'Seu nome com letras minusculas: {nome.lower()}.')
print('Seu nome tem {} letras.'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras.'.format(nome.find(' ')))